version: "3"
services:
  node:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: vsce-nodejs
    environment:
      - TZ=Asia/Tokyo
    working_dir: /home/node
    volumes:
      - .:/home/node
    tty: true
